api_hash: d773d0512e877cd3742fa14bd6cb5086
api_id: 17585709
chat_id: -1001302243530
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- photo
- video
- document
- voice
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
  
